name: Mabin Log
description: Study Site
meta_description: ""

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "http://mabinlog.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Mabin"

# Disqus config
disqus-shortname: ""

# possible future post
future: true

# <br>(줄 바꿈) 을 텍스트가 아닌 문자 그대로 해석함
kramdown:
  hard_wrap: true